server:
  port: 9000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: case-service
          uri: lb://case-service
          predicates:
            - Path=/cases/**

        - id: people-service
          uri: lb://people-service
          predicates:
            - Path=/people/**

        - id: evidence-service
          uri: lb://evidence-service
          predicates:
            - Path=/evidences/**

        - id: workflow-service
          uri: lb://workflow-service
          predicates:
            - Path=/tasks/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**

        - id: audit-service
          uri: lb://audit-service
          predicates:
            - Path=/audit-logs/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_URI}
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: false
    hostname: api-gateway
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG