server:
  port: 9000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

      routes:
        - id: case-service
          uri: lb://case-service
          predicates:
            - Path=/cases/**

        - id: people-service
          uri: lb://people-service
          predicates:
            - Path=/people/**

        - id: evidence-service
          uri: lb://evidence-service
          predicates:
            - Path=/evidence/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_URI}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: false
    hostname: api-gateway
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG